import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi eveniet corrupti quis praesentium enim? Iusto fuga consectetur officia, enim alias ad numquam natus dolorem? Laboriosam repellendus ratione accusantium officiis quo.</p>
        {children}
      </body>
    </html>
  )
}
